# Generated by Django 6.0 on 2025-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='txid',
            field=models.CharField(blank=True, max_length=200, verbose_name='Transaction ID for Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='txid_proof',
            field=models.ImageField(blank=True, null=True, upload_to='txid_proofs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
