# Generated by Django 6.0 on 2025-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_customer_name_order_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
