# Generated by Django 6.0 on 2025-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_withdrawaltaxsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='signup_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
