# Generated by Django 6.0 on 2025-12-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wallet_signup_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_proof_content_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_proof_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='txid_proof_content_type',
            field=models.CharField(blank=True, default='image/jpeg', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='txid_proof_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_content_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_content_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_proof',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='txid_proof',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
