# Generated by Django 6.0 on 2025-12-24 09:55

from django.db import migrations


def fix_constraints(apps, schema_editor):
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'core_deposit' 
            AND column_name IN ('deposit_proof_content_type', 'deposit_proof_filename')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        if 'deposit_proof_content_type' in existing_columns:
            cursor.execute("""
                ALTER TABLE core_deposit 
                DROP COLUMN deposit_proof_content_type;
            """)
        
        if 'deposit_proof_filename' in existing_columns:
            cursor.execute("""
                ALTER TABLE core_deposit 
                DROP COLUMN deposit_proof_filename;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_deposit_proof_content_type_constraint'),
    ]

    operations = [
        migrations.RunPython(fix_constraints, migrations.RunPython.noop),
    ]
