# Generated by Django 6.0 on 2025-12-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fix_order_product_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
